build:
  version: "1.0"

loans:
  message: "Welcome to EazyBank loans related local prod APIs "
  contactDetails:
    name: "Owner contact - Product Owner"
    email: "product.owner@gmail.com"
  onCallSupport:
    - (777) 555-5555
    - (777) 523-5555